CREATE TABLE IF NOT EXISTS tb_agricola (
    cod_uf INTEGER,
    cod_municipio INTEGER,
    cod_distrito INTEGER,
    cod_subdistrito INTEGER,
    situacao TEXT,
    nom_tip_seglogr TEXT,
    nom_titulo_seglogr TEXT,
    nom_seglogr TEXT,
    num_endereco TEXT,
    dsc_modificador TEXT,
    nom_comp_elem1 TEXT,
    val_comp_elem1 REAL,
    nom_comp_elem2 TEXT,
    val_comp_elem2 REAL,
    nom_comp_elem3 TEXT,
    val_comp_elem3 REAL,
    nom_comp_elem4 TEXT,
    val_comp_elem4 REAL,
    nom_comp_elem5 TEXT,
    val_comp_elem5 REAL,
    latitude REAL,
    longitude REAL,
    altitude REAL,
    desc_localidade TEXT,
    cod_especie INTEGER,
    cep TEXT
);